### ISSUE TITLE
output image is massively bloated compared to input image

### ISSUE THREAD

**Issue by Pyroseza** [sggts04/dankcli#2]
When I run the program, I choose a JPG image of 905KB and add a single line to it, the output file type changes to PNG and is 8.3MB in size.

Here's my command:
`python -m dankcli "84890886.jpg" "When you finally make your first meme, time to take over the world"`

Input image
![84890886](https://user-images.githubusercontent.com/8463626/54390797-3d125e80-469b-11e9-8f5d-cf1a2e8429a4.jpg)

Output image
![meme1](https://user-images.githubusercontent.com/8463626/54393168-6c2bce80-46a1-11e9-90b9-11c6e1f3d166.png)

**Comment by Pyroseza** [comment]
issue fixed in this pull request
https://github.com/sggts04/dankcli/pull/3

**Comment by Pyroseza** [comment]
New image is no longer bloated 👍 

![meme1](https://user-images.githubusercontent.com/8463626/54393201-7bab1780-46a1-11e9-9730-972888373aaa.jpg)

**Comment by sggts04** [comment]
Merged PR and updated to v0.4.3, thanks! The issue probably was that JPEGs and JPGs don't have alpha channels but I was saving them as RGBA as PNG so basically adding a new layer which made them bloat
