### ISSUE TITLE
Two features: Black background and white text and better names for the images saved

### ISSUE THREAD

**Issue by kavinsood** [sggts04/dankcli#7]
**Is your feature request related to a problem? Please describe.**
I am frustrated by the names of pictures saved. Also, an option to have black background with white or colorful text would be cool.

**Describe the solution you'd like**
A better way of naming would be original name of file + " meme". If multiple memes of the same template are made, then (1),(2) and so on can be added. For the second one, the option to switch colors of text could be a option you add like `-black`

**Describe alternatives you've considered**
To make dark text, Doing  `python -m dankcli "image.png" " "` and then coloring the white part and adding text with paint.net or anything really. For the naming I haven't been able to come up with something. The names are so bizarre.

**Comment by sggts04** [comment]
@k2s09 what kind of naming convention are you looking for? There is already `-f` flag that you can use to specify your own file name by the way

**Comment by kavinsood** [comment]
Actually I didn't know about the `-f` flag to choose a name, I will use that for now. That solves my problem. But if you can change the naming conventions, taking the original name of the image and concat " meme"? How does that sound? Anways, I had raised this issue way back when I discovered it and starting using it. I am not frustrated or really bothered by it now. I had a huge meme templates folder and used to use this tool to make memes there. Due to the size, I didn't ever scroll and find images, just looked at the names. But now I save the memes in a different folder and rename them myself. I have overcome it.

This issue is like a scar, a blemish on a smooth white marble masterpiece of a statue and it breaks my heart to see that my issue raised here implies to anyone who looks at this page that this beautifully crafted piece of software has bugs or issues of any sort. 

So let me use this opportunity to close this issue and make this github page devoid of any issues, filling any left void in this project, making it truly complete.
